services:
  testenv:
    image: locknessie-testenv
    build:
      context: .
      dockerfile: ./dockerfiles/test.Dockerfile
      args:
        LOCKNESSIE_ENVIRONMENT: development
    ports:
      - "8200:8200"
      - "1234:1234"
    container_name: locknessie-testenv
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - LOCKNESSIE_ENVIRONMENT=development