[project]
name = "nessie-oauth2"
version = "0.0.1"
description = "Nessie OAuth2 provides a client and server pair for authentication to Nessie with OpenID."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "msal>=1.32.3",
    "pyjwt>=2.10.1",
]
